### ISSUE TITLE
Running the benchmark fails with "No such file"

### ISSUE THREAD

**Issue by rolandtritsch** [typelead/eta-benchmarks#10]
When installing/cloning this from scratch, running it fails, because Build.hs needs eta on the path (which is not necessarily the case) to do/run `eta --numeric-version` (in Build.hs; line 151).

Options to fix this ...

* Put a requirement into the README to make sure that eta is on the path (and document a/the best way to put eta on the path (right now I copy it manually from ~/.etlas/binaries/... to ~/.local/bin)).
* Change the way Build.hs is looking for the version number

Not sure what the best/right way is to fix this.

Thoughts?

**Comment by rahulmutt** [comment]
`etlas exec eta -- --numeric-version` should probably be the appropriate replacement. It'll use whatever the user that `etlas select`'d. Happy to accept a PR for this.

**Comment by rolandtritsch** [comment]
Solved with PR #16.
